version: '3.8'

services:
  resume-screener:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./uploads:/app/uploads